version: "3.3"

services:
  mysql-db:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuserpwd
      - MYSQL_DATABASE=titanic_db
    expose:
      - "3306"      
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  node-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    expose:
      - "5000"      
    ports:
      - "5000:5000"
    volumes:
      - ./server:/opt/app:delegated
      - ./server/package.json:/opt/package.json
      - ./server/package-lock.json:/opt/package-lock.json
      - notused:/opt/app/node_modules
    networks:
      - titanic-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "80:3000"
    volumes:
      - ./client:/opt/app:delegated
      - ./client/package.json:/opt/package.json
      - ./client/package-lock.json:/opt/package-lock.json
      - notused:/opt/app/node_modules
    networks:
      - titanic-network

networks:
  titanic-network:
    driver: bridge

volumes:
  db_data:
  notused:

